[workspace]
authors = ["ejaz-karim <78738965+ejaz-karim@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "backend"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
requests = ">=2.32.3,<3"
beautifulsoup4 = ">=4.13.4,<5"
